(ns json-ast-harness
  (:require [harness.cli :as cli]))

(def usage cli/usage)
(def json-safe cli/json-safe)
(def minimal-ast cli/minimal-ast)

(def check-json cli/check-json)
(def compile-json cli/compile-json)
(def semantic-check cli/semantic-check)
(def smoke cli/smoke)
(def gui-smoke cli/gui-smoke)
(def gui-run cli/gui-run)
(def gui-open cli/gui-open)
(def gui-jar cli/gui-jar)
(def dry-run cli/dry-run)
(def chat-completion cli/chat-completion)
(def check-and-compile cli/check-and-compile)
(def run-json cli/run-json)
(def chat-ping cli/chat-ping)
